feat(CRUD accommodation facilities)Travel admins should be able to CR…
atlp-rwanda/elite-bn-be pull request #30
Opened 2022-06-03 21:42 UTC by munyanezaarmel

#### What does this PR do?

 Travel admins should be able to CRUD accommodation facilities

#### Description of Task to be completed?

have the following endpoints working

-  **GET /api/ accomodation/**
- 
-  **POST /api/ accomodation/**
- 
- **GET /api/ accomodation/**
- 
- **GET /api/ accomodation/<accomodation_id>**
- 
- **PUT /api/ accomodation/<accomodation_id>**
- 
- **DELETE /api/ accomodation/<accomodation_id>**
- 
- **GET /api/ room/**
- 
- **POST /api/ room/**
- 
- **GET /api/ room/**
- 
- **GET /api/ room/<room_id>**
- 
- **PUT /api/ room/<room_id>**
- 
- **DELETE /api/ room/<room_id>**

#### How should this be manually tested?
after cloning this repo cd into it and run npm run start

-  using postman test every endpoint above with this header:

 key: content-type value : application/json

#### Any background context you want to provide?
there implementation of  accomodation services and amenities in the services folder
#### What are the relevant pivotal tracker stories?
(#182201574)[https://www.pivotaltracker.com/story/show/182201574]

2022-06-13 20:37 UTC, kalisaNkevin requested changes
rebase needed

2022-06-20 15:41 UTC, ishimweeli submitted a review, later dismissed

2022-06-22 07:11 UTC, kalisaNkevin approved these changes, later dismissed
running successfuly

2022-06-22 10:30 UTC, didasmbalanya requested changes
- Make sure your data is validated before being engaged in any controller
- Make sure your models and migrations match both in relations and types
- Testing should also include a lot of the data not just status code. more test cases needed

2022-06-22 10:30 UTC, didasmbalanya commented on .env.example
> +NODE_ENV=test
remove

2022-06-22 10:30 UTC, didasmbalanya commented on src/services/locationServices.js
> +    console.log('############# id')
remove console.log

2022-06-22 10:30 UTC, didasmbalanya commented on src/controllers/accomodation.js
> +        return ApplicationError.internalServerError(
this is error 404, not 500 - internal server error

2022-06-22 10:30 UTC, didasmbalanya commented on src/controllers/accomodation.js
> +      console.log(req.body)
remove console.log

2022-06-22 10:30 UTC, didasmbalanya commented on test/country.spec.js
> +  })
This is tests for accomodaton ! not validation

2022-06-22 10:30 UTC, didasmbalanya commented on src/routes/accomodationRouter.js
> +  '/v1/accomodation/create',
add a middleware to validate all endpoints that create data. use JOI validation!

2022-06-22 10:30 UTC, didasmbalanya commented on src/database/migrations/20220610110828-create-accomodation.js
> +      },
missing relationship to location table

2022-06-22 10:30 UTC, didasmbalanya commented on src/database/migrations/20220610111626-create-room.js
> +      },
add relationship

2022-06-22 10:30 UTC, didasmbalanya commented on src/database/models/accomodation.js
> +    accomodationDescription: DataTypes.STRING,
not null

2022-06-22 10:30 UTC, didasmbalanya commented on src/database/models/accomodation.js
> +    accomodationDescription: DataTypes.STRING,
not null

2022-06-22 10:30 UTC, didasmbalanya commented on src/index.js
>  import dotenv from 'dotenv'
```suggestion
import 'dotenv/config'
```

2022-06-26 07:54 UTC, munyanezaarmel commented on src/routes/accomodationRouter.js
> +  '/v1/accomodation/create',
done

2022-06-26 07:55 UTC, munyanezaarmel commented on src/database/models/accomodation.js
> +    accomodationDescription: DataTypes.STRING,
done

2022-06-26 07:55 UTC, munyanezaarmel commented on src/database/models/accomodation.js
> +    accomodationDescription: DataTypes.STRING,
done

2022-06-26 07:56 UTC, munyanezaarmel commented on src/database/migrations/20220610111626-create-room.js
> +      },
done

2022-06-26 07:56 UTC, munyanezaarmel commented on src/database/migrations/20220610110828-create-accomodation.js
> +      },
done

2022-06-26 07:56 UTC, munyanezaarmel commented on src/controllers/accomodation.js
> +      console.log(req.body)
done

2022-06-26 07:56 UTC, munyanezaarmel commented on src/controllers/accomodation.js
> +        return ApplicationError.internalServerError(
done

2022-06-26 08:00 UTC, munyanezaarmel commented on src/services/locationServices.js
> +    console.log('############# id')
done

2022-06-26 08:02 UTC, munyanezaarmel commented on test/country.spec.js
> +  })
done

2022-06-27 08:58 UTC, Julienish14 reviewed
I think a country must be unique, you have unused findOne method in countryServise. please use it to avoid country duplication in database

Fixed check again

2022-06-27 12:35 UTC, kalisaNkevin commented
work on the tests

2022-06-27 14:51 UTC, kalisaNkevin submitted a review, later dismissed

2022-06-28 07:24 UTC, Julienish14 approved these changes

2022-06-28 07:38 UTC, Julienish14 submitted a review, later dismissed
I have a little question? aren't this supposed to be protected?

2022-06-28 08:00 UTC, ishimweeli approved these changes

2022-06-28 08:02 UTC, ishimweeli submitted a review, later dismissed

2022-06-28 08:14 UTC, kalisaNkevin submitted a review, later dismissed

2022-06-28 13:53 UTC, kalisaNkevin submitted a review, later dismissed

2022-06-29 13:04 UTC, Ntare22 requested changes, later dismissed
Please remove the console.logs in your PR.

2022-06-29 13:04 UTC, Ntare22 commented on src/controllers/accomodation.js
> +      console.log(error);
Please remove the console logs.

2022-06-29 13:04 UTC, Ntare22 commented on src/controllers/accomodation.js
> +      console.log(error);
Remove this console too.

2022-06-29 13:10 UTC, munyanezaarmel commented on src/controllers/accomodation.js
> +      console.log(error);
done

2022-06-29 17:03 UTC, Francoise02 approved these changes, later dismissed

2022-06-29 17:38 UTC, kalisaNkevin submitted a review, later dismissed

2022-07-03 12:54 UTC, Francoise02 approved these changes

2022-07-03 14:17 UTC, uwishema11 approved these changes

2022-07-03 14:52 UTC, Julienish14 approved these changes

2022-07-04 05:17 UTC, kalisaNkevin approved these changes

2022-07-04 08:46 UTC, ishimweeli approved these changes
working well

2022-07-05 15:05 UTC, didasmbalanya approved these changes

2022-07-05 15:05 UTC, merged