Ch-deploy-base-application-to-heroku-182201564
atlp-rwanda/elite-bn-be pull request #39
Opened 2022-06-10 06:55 UTC by ishimweeli

#### What does this PR do?
deployed version on heroku
#### How should this be manually tested?
heroku logs --app elite-bn-be
#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
182201564

2022-06-10 14:20 UTC, Francoise02 requested changes
Remove the SSL in `src/database/config/config.js` Otherwise there is an error `Error: The server does not support SSL connections`

2022-06-10 14:36 UTC, Francoise02 submitted a review, later dismissed

2022-06-10 14:37 UTC, Francoise02 commented
Elaborate more on how we can manually test your PR @ishimweeli

2022-06-16 10:44 UTC, kalisaNkevin approved these changes

2022-06-16 11:13 UTC, Ntare22 approved these changes

2022-06-16 11:13 UTC, merged