Ft reset password via email 182201573
atlp-rwanda/elite-bn-be pull request #48
Opened 2022-06-14 13:06 UTC by uwishema11

#### What does this PR do?
it  allow to request reset  password in case the user forgot their login credentials

#### How should this be manually tested?

after cloning the PR and start the server you can test it with postman or swagger
using postman you can use the following endpoint
POST /api/v1/user/forgotPassword
.PUT /api/v1/user/resetPassword/resetToken

#### Any background context you want to provide?
after requesting to reset password , a link to reset will be sent to the providede email

#### What are the relevant pivotal tracker stories?
#182201573

2022-06-22 14:27 UTC, didasmbalanya requested changes

2022-06-22 14:27 UTC, didasmbalanya commented on package.json
> +    "cross-env": "^7.0.3",
is this a dependancy or a dev dependency ?

2022-06-22 14:27 UTC, didasmbalanya commented on src/controllers/userController.js
> +import { sendEmailOnResetPassword } from "../views/resetEmailTemplate"
remove eslint disable on line 1

2022-06-22 14:27 UTC, didasmbalanya commented on src/services/userServices.js
> +    passwordResetToken:resetToken
This does not need to be saved on the DB. you can save it on redis and remove it when a user uses the token

2022-06-22 14:27 UTC, didasmbalanya commented on src/controllers/userController.js
> +        await userService.update(email,resetToken);
You can store the token on Redis. not in the DB

2022-06-22 14:27 UTC, didasmbalanya commented on src/controllers/userController.js
> +            `${process.env.BASE_URL}/resetPassword/${user.passwordResetToken}`))
The link of the backend API (BASEURL) should be retrieved from the current server. From the req object. Please look into that

2022-06-22 14:27 UTC, didasmbalanya commented on src/views/resetEmailTemplate.js
> +export const sendEmailOnResetPassword = (
use a better name. 'passwordResetTemplate'

2022-06-22 14:27 UTC, didasmbalanya commented on src/controllers/userController.js
> +            const token = req.params.passwordResetToken
token can also be validated by JOI.

And do validation with a middleware, not in the controller

2022-06-22 14:27 UTC, didasmbalanya commented on src/controllers/userController.js
> +                    message:'we could not find a match with this link'
put in the validation middleware and use a better error message

2022-06-22 14:27 UTC, didasmbalanya commented on src/controllers/userController.js
> +            await jwt.verify(token,process.env.JWT_RESET_TOKEN_SECRET,(error,decodedToken)=>{
use the "jwtAccessTokenDecode" function in the helpers. Make it a reusable function for decoding multiple tokens

2022-06-22 14:27 UTC, didasmbalanya commented on src/services/userServices.js
> +return user;
no difference as calling userService.update

2022-06-22 14:27 UTC, didasmbalanya commented on src/controllers/userController.js
> +            await userService.resetedPassword(token,newPassword);
use userService.update, does the same thing

2022-06-22 14:27 UTC, didasmbalanya commented on src/controllers/userController.js
> +            })
This can not be the default error. There are so many possible errors that can be caught here

2022-06-22 14:27 UTC, didasmbalanya commented on src/controllers/userController.js
> +        console.log(error);
remove

2022-06-22 14:27 UTC, didasmbalanya commented on src/database/migrations/20220605123824-create-user.js
>  /*eslint-disable*/
remove

2022-06-22 14:27 UTC, didasmbalanya commented on src/database/migrations/20220605123824-create-user.js
> +/* const { DataTypes } = require("sequelize/types"); */
remove

2022-06-22 14:27 UTC, didasmbalanya commented on src/database/migrations/20220605123824-create-user.js
>        firstName: {
do not ever update a migration file that has been merged. Create a new migration to add a column to the Users table

2022-06-22 14:27 UTC, didasmbalanya commented on src/utils/email/sendPaawordLink.js
> +        if (process.env.NODE_ENV === 'production') {
```suggestion
        if (process.env.NODE_ENV !== 'test') {
```

So that when someone is testing it locally in the "development" env they can see the email being sent

2022-06-22 14:27 UTC, didasmbalanya commented on src/utils/helpers/generateToken.js
> +export const generateResetToken=(id)=>{
find a way of making "generateAccessToken" more reusable and rename it to generateToken

2022-06-22 14:27 UTC, didasmbalanya commented on test/resetPassword.spec.js
> +    }
why are you using them as objects ?

2022-06-22 14:27 UTC, didasmbalanya commented on test/resetPassword.spec.js
> +    });
use one, since they will both do the same thing

2022-06-22 14:27 UTC, didasmbalanya commented on test/resetPassword.spec.js
> +  expect(res).to.have.status(404);
should not be a 404 for a validation error

2022-07-04 17:24 UTC, munyanezaarmel reviewed
there is no dev script in your package json i cant connect to the server in development

2022-07-06 13:21 UTC, Francoise02 approved these changes

2022-07-06 14:45 UTC, ishimweeli approved these changes

2022-07-06 16:55 UTC, kalisaNkevin approved these changes

2022-07-07 07:01 UTC, munyanezaarmel approved these changes

2022-07-07 15:38 UTC, Ntare22 approved these changes

2022-07-07 15:38 UTC, merged