Ft google facebook auth 182201570
atlp-rwanda/elite-bn-be pull request #53
Opened 2022-06-21 14:39 UTC by Francoise02

…ation via Google and Facebook

What does this PR do?
Allow users to log in with their Google and Facebook

How should this be manually tested?
Create Google Client and Secret IDs: you can follow this [tutorial](https://www.youtube.com/watch?v=xH6hAW3EqLk) for guidance.

Create Facebook Client and secret IDs. You can follow this [tutorial](https://www.youtube.com/watch?v=jMVlSDU-6l4) to do so.

Follow the.env.example file to create your .env file and add your credentials

Run npm start

Check these endpoints:

GET : auth/google
GET : auth/facebook
Any background context you want to provide?
You need to have both the endpoint path and a correct callback_url to successfully test this PR.

What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/182201570

2022-06-21 16:30 UTC, Julienish14 approved these changes

2022-06-21 16:37 UTC, Julienish14 approved these changes, later dismissed

2022-06-21 21:31 UTC, Julienish14 submitted a review, later dismissed

2022-06-21 21:33 UTC, uwishema11 submitted a review, later dismissed

2022-06-22 08:19 UTC, didasmbalanya requested changes

2022-06-22 08:19 UTC, didasmbalanya commented on .env.example
> +GOOGLE_CLIENT_SECRET= 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
remove these values from github. they are private.

2022-06-22 08:19 UTC, didasmbalanya commented on .env.example
> +FACEBOOK_CLIENT_SECRET= 0b7fb4122db92dadc84325e4242c87f4
private values. Should never be pushed to Github

2022-06-22 08:19 UTC, didasmbalanya commented on src/controllers/googleFacebook.js
> +  console.log(user)
remove console

2022-06-22 08:19 UTC, didasmbalanya commented on src/controllers/googleFacebook.js
> +  console.log(token)
remove

2022-06-22 08:19 UTC, didasmbalanya commented on src/routes/googleFacebook.js
> +/* eslint-disable */
Why are you disabling eslint? Please remove this comment

2022-06-22 08:19 UTC, didasmbalanya commented on src/controllers/index.js
> +/* eslint-disable */
remove this

2022-06-22 08:19 UTC, didasmbalanya commented on src/controllers/googleFacebook.js
> +/* eslint-disable */
remove

2022-06-22 08:19 UTC, didasmbalanya commented on src/database/migrations/20220321064904-authorizedUser.js
> +/* eslint-disable */
remove

2022-06-22 08:19 UTC, didasmbalanya commented on src/database/migrations/20220321064904-authorizedUser.js
> +};
You do not need this table

2022-06-22 08:19 UTC, didasmbalanya commented on src/database/migrations/20220321064904-authorizedUser.js
> +};
We use JWTs to identify authorized users

2022-06-22 08:19 UTC, didasmbalanya commented on src/database/migrations/20220605123824-create-user.js
> +        primaryKey: true
do not touch old migration files.
Write a new migration file and do whatever updates!

2022-06-22 08:19 UTC, didasmbalanya commented on src/database/migrations/20220605123824-create-user.js
>          type: Sequelize.ENUM,
do all this changes in a separate migration file

2022-06-22 08:19 UTC, didasmbalanya commented on src/database/models/authorized.js
> +/* eslint-disable*/
remove

2022-06-22 08:19 UTC, didasmbalanya commented on src/database/models/authorized.js
> +
what is this 'authorizedUser' model for ?

2022-06-22 08:19 UTC, didasmbalanya commented on src/database/models/index.js
> +/* eslint-disable*/
remove

2022-06-22 08:19 UTC, didasmbalanya commented on src/database/seeders/user.js
> +/* eslint-disable*/
remove

2022-06-22 08:19 UTC, didasmbalanya commented on src/index.js
> +/* eslint-disable */
remove

2022-06-22 08:19 UTC, didasmbalanya commented on src/routes/index.js
> +/* eslint-disable */
remove

2022-06-22 08:19 UTC, didasmbalanya commented on src/services/googleFacebook.js
> +/* eslint-disable */
remove

2022-06-22 08:19 UTC, didasmbalanya commented on src/services/googleFacebook.js
> +      // { user_id: userData.id, refreshToken }
remove commented code if it adds no value

2022-06-22 08:19 UTC, didasmbalanya commented on src/services/userServices.js
> +/* eslint-disable */
remove

2022-06-22 08:19 UTC, didasmbalanya commented on src/utils/helpers/generateToken.js
> +/* eslint-disable */
remove

2022-06-23 10:02 UTC, kalisaNkevin submitted a review, later dismissed

2022-06-23 14:13 UTC, ishimweeli submitted a review, later dismissed
running well on my end

2022-06-23 14:25 UTC, Julienish14 approved these changes, later dismissed

2022-06-24 20:36 UTC, Julienish14 approved these changes

2022-06-25 09:54 UTC, munyanezaarmel approved these changes

2022-06-25 09:55 UTC, Julienish14 approved these changes

2022-06-25 11:35 UTC, kalisaNkevin approved these changes

2022-06-25 13:45 UTC, uwishema11 approved these changes

2022-06-27 06:50 UTC, Ntare22 approved these changes
LGTM

2022-06-27 06:54 UTC, merged