chore(setuptesting):Setup testing
atlp-rwanda/elite-bn-be pull request #7
Opened 2022-05-22 21:43 UTC by uwishema11

####What does this PR do?
it set up unit testing with mocha chai

####how should this be manually tested?
after cloning a repo cd into it and  run npm  test

####any background context you want to provide?
installed mocha chai and chai-http in package json

####what are the relevant pivotal tracker stories?
#182201509

2022-05-23 02:29 UTC, kalisaNkevin approved these changes, later dismissed

2022-05-23 10:26 UTC, munyanezaarmel commented
Great Job @uwishema11  add pivotal tracker id on your branch name ,edit the pull request template file and paste the task description you specify in comment above

2022-05-23 10:26 UTC, munyanezaarmel approved these changes, later dismissed

2022-05-25 04:50 UTC, Ntare22 requested changes, later dismissed
Great stuff Celine, please rebase your work.

2022-05-26 08:55 UTC, didasmbalanya requested changes
Add a dummy test as well to make sure it is working

2022-05-26 20:42 UTC, kalisaNkevin approved these changes

2022-05-27 15:08 UTC, Julienish14 approved these changes

2022-05-27 15:50 UTC, didasmbalanya approved these changes

2022-05-27 15:50 UTC, merged