bug-fix-logout
atlp-rwanda/elite-bn-be pull request #75
Opened 2022-07-22 15:11 UTC by ishimweeli

#### What does this PR do?
logout using redis
#### How should this be manually tested?
use postman or swagger and call logout api from uder ags

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
#1822201571

2022-07-29 18:45 UTC, kalisaNkevin submitted a review, later dismissed

2022-08-09 20:00 UTC, kalisaNkevin submitted a review, later dismissed

2022-08-09 20:41 UTC, ericus123 commented on src/controllers/accomodation.js
> +console.log(error)
remove this

2022-08-09 20:41 UTC, ericus123 commented on src/controllers/location.js
remove this

2022-08-09 20:41 UTC, ericus123 commented on src/controllers/location.js
> +      // ApplicationError.internalServerError({ message: error }, res);
what is this doing

2022-08-09 20:43 UTC, ericus123 requested changes

2022-08-09 20:43 UTC, ericus123 commented on src/controllers/userController.js
> +console.log(req.user)
please remove all the logs since they are only there for debugging.

2022-08-09 20:43 UTC, ericus123 commented on src/utils/helpers/initRedis.js
> +
remove unused codes

2022-08-09 21:47 UTC, ericus123 approved these changes

2022-08-09 21:47 UTC, merged